project:
  type: website
  output-dir: docs
  resources: static

# sidebar: false
# 
# # Hides the navbar on this page
# navbar: false
search: false
website:
  title: "Elena Chechik"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: About me
      - text: "Publications"
        file: pubs.qmd
      # - text: "CV"
      #   file: files/cv_chechik_2024_GitHub.pdf


format:
  html:
    theme: 
      light: simplex
    css: styles.css
    toc: true


